export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const SET_CURRENT_COUNTRY = 'SET_CURRENT_COUNTRY';
export const UPDATE_SORT_BY = 'UPDATE_SORT_BY';
export const SET_COUNTRIES = "SET_COUNTRIES";
export const SET_FILTER_BY = "SET_FILTER_BY";
